databases:
  - name: dicib-db
    plan: free

services:
  - type: web
    name: dicib-ctf
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dicib-db
          property: connectionString
      - key: ALFA_PASSWORD
        sync: false
      - key: BRAVO_PASSWORD
        sync: false
      - key: CHARLY_PASSWORD
        sync: false
      - key: DELTA_PASSWORD
        sync: false
      - key: ADMIN_USER
        value: WAZOWSKI
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
